version: 2.0
jobs:
  build:
    branches:
      only:
        - production
        - master
        - microsim
    working_directory: ~/npct/pct-shiny
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/ruby:2.6
    steps:
    - checkout
    - run: 'bash scripts/deploy.sh'
