version: 2
jobs:
  build:
    branches:
      only:
        - production
    working_directory: ~/npct/pct-shiny
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: ubuntu:18.04
    steps:
    - run: 'git push git@npt1.vs.mythic-beasts.com:pct-shiny ${CIRCLE_SHA1}:${CIRCLE_BRANCH} -f'
  build:
    branches:
      only:
        - master
        - microsim
    working_directory: ~/npct/pct-shiny
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: ubuntu:18.04
    steps:
    - run: 'git push git@npct0.vs.mythic-beasts.com:pct-shiny ${CIRCLE_SHA1}:${CIRCLE_BRANCH} -f'
