version: 2.0
jobs:
  build:
    branches:
      only:
        - production
    working_directory: ~/npct/pct-shiny
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: debian:9
    steps:
    - run: 'apt update'
    - run: 'apt install -y git'
    - run: 'git push git@npt1.vs.mythic-beasts.com:pct-shiny ${CIRCLE_SHA1}:${CIRCLE_BRANCH} -f'
  build:
    branches:
      only:
        - master
        - microsim
    working_directory: ~/npct/pct-shiny
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: debian:9
    steps:
    - run: 'apt update'
    - run: 'apt install -y git'
    - run: 'git push git@npct0.vs.mythic-beasts.com:pct-shiny ${CIRCLE_SHA1}:${CIRCLE_BRANCH} -f'
