---
author: "The Propensity to Cycle Team"
date: "Last updated: `r format(Sys.Date(), format = '%m-%d-%y')`"
output:
  html_document:
    includes:
      in_header: ../static/header.html
      before_body: ../static/doc_prefix.html
  css: ../www/style/bootstrap.min.css
---

<!--If editing this page use index.Rmd which compiles into index.html-->

Welcome to the prototype of the National Propensity to Cycle Tool for England (PCT-England) 
This tool provides evidence to guide cycling investment in England. Within each region, the tool shows cycling levels at the small area level and between areas based on 2011 Census commuting data. It also shows what spatial distribution of cycling might be expected as cycling increases.

The cycling trips can be allocated to the road network, based on the fastest cycling route. The purpose of the route allocation is to see on which routes the most provision might be necessary as cycling grows rather than to show where people currently cycle. We recognise that many people currently choose longer routes to avoid busy roads, but for cycling to achieve its potential will require the creation direct routes on which people feel safe. The purpose of the route allocation is therefore to see on which routes the most provision might be necessary as cycling grows rather than to show where people currently cycle.

Users can select different overall cycling scenarios, such as ‘Go Dutch’ or ‘Ebikes’, and can then see what this might mean for cycling levels in each small area and along the network. The model estimates cycling potential based upon trip distances and hilliness. Therefore, it highlights the greatest unmet potential in areas that currently have high numbers of short trips in relatively flat areas but where people are not currently cycling.

At the moment the model just shows commuting main mode trips but additional layers will be added to future versions.