---
output: 
  html_document:
    keep_md: false
  
---


```{r echo=FALSE}
source("../m/pct_shiny_funs.R")
sha <- readRDS("download_params_sha_current.rds")

```

<!--html_preserve-->
<div class='container'>
  <div class='row maintext' id='maintext'>
    <div class='col-md-2 text-left' style='padding-top:10px;'>
      <div style='padding-bottom:10px;'><a class='natdownloadlinks' href='#natcommutezones'>Zones data</a></div>
      <div style='padding-bottom:10px;'><a class='natdownloadlinks' href='#natcommutemsoalines'>MSOA lines data</a></div>
      <div style='padding-bottom:10px;'><a class='natdownloadlinks' href='#natcommutelsoalines'>LSOA lines data</a></div>
    </div>

    <div class='col-md-9'>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h3>National Data</h3>
        <p>This page contains data downloads for the whole of England. These are available as CSV files containing the zone and line baseline and scenario data, and in geographic files that can be read by R (.Rds) or GIS programs such as QGIS (.geojson).  Very large geographic files are available in R format only.</p>
        <p>Please be aware that equivalent files for different geographies have <b>the same file name</b> when downloaded (e.g. 'z_all.geojson' for both the MSOA and LSOA national zones files).  To avoid confusion you may want to rename those files or save them in labelled folders.</p>
      </div>
      
      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h4><a name='natcommutezones'></a>Commuting data for zones</h4>
          <p>Download the Census 2011 and scenario attribute data for all zones in England.</p>
          <ul>
            <li>Zones (local authorities)*:`r download_link_national_data("lad", "commute", "", formats = c('Rds', 'geojson'))` - `r download_link_codebook("lad_codebook", "commute", repo_sha = sha$repo_sha)`
            <li>Zones (MSOA):`r download_link_national_data("z_all", "commute", "msoa", formats = c('Rds', 'geojson'))` - `r download_link_codebook("z_codebook", "commute", repo_sha = sha$repo_sha)`
            </li>
            <li>Zones (LSOA):`r download_link_national_data("z_all", "commute", "lsoa", formats = c('Rds', 'geojson'))` - `r download_link_codebook("z_codebook", "commute", repo_sha = sha$repo_sha)` </li>
          </ul>
          <p>* Data aggregated from the LSOA zones file. Note that different units are used for the health economic savings (million pounds not pounds) and carbon savings (tonnes not kilograms of CO2e).</p>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h4>Commuting data for lines</h4>
        <p>Download the Census 2011 and scenario data for all lines starting or ending in England.</p>
        <p>In the 'All flows' files, destinations are grouped as 'Other' for origin-destination pairs with a fastest-route distance >30km, or with a destination outside England or Wales. In addition, for the LSOA 'All flows' file, destinations are grouped as 'Under 3' for origin-destination pairs where the bidirectional number of commuters (by any mode) would be 1 or 2. This is done for data protection reasons.</p>
        <p>The 'Straight lines', 'Fast route' and 'Quieter routes' files only include between-zone lines with fast route distance under 20km. In addition, the minimum number of commuters (by any mode, in either direction) must be 10 (MSOA) or 5 (LSOA).</p>
        <p>The LSOA route network includes all between-zone LSOA flows with fast route distance under 20km (with no minimum number of commuters).</p>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
         <h4><a name='natcommutemsoalines'></a>MSOA-level lines data</h4>
          <ul>
            <li>All flows (attribute data only): `r download_link_national_data("od_all_attributes", "commute", "msoa", formats = c('csv'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Centroids & within-zone travel: `r download_link_national_data("c_all", "commute", "msoa", formats = c('Rds', 'geojson'))` - `r download_link_codebook("c_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Straight lines: `r download_link_national_data("l_all", "commute", "msoa", formats = c('Rds'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Fast routes: `r download_link_national_data("rf_all", "commute", "msoa", formats = c('Rds'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Quieter routes: `r download_link_national_data("rq_all", "commute", "msoa", formats = c('Rds'))` - `r download_link_codebook("rq_codebook", "commute", repo_sha = sha$repo_sha)`</li>
          </ul>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h4><a name='natcommutelsoalines'></a>LSOA-level lines data</h4>
          <ul>
            <li>All flows (attribute data only): `r download_link_national_data("od_all_attributes", "commute", "lsoa", formats = c('csv'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Centroids & within-zone travel: `r download_link_national_data("c_all", "commute", "lsoa", formats = c('Rds', 'geojson'))` - `r download_link_codebook("c_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Straight lines: `r download_link_national_data("l_all", "commute", "lsoa", formats = c('Rds'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Fast routes: `r download_link_national_data("rf_all", "commute", "lsoa", formats = c('Rds'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Quieter routes: `r download_link_national_data("rq_all", "commute", "lsoa", formats = c('Rds'))` - `r download_link_codebook("rq_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Route network (LSOA): Census 2011 `r download_link_national_data("ras_bicycle_all", "commute", "lsoa", formats = c('tif'))` ; Government Target `r download_link_national_data("ras_govtarget_all", "commute", "lsoa", formats = c('tif'))` ; Gender Equality `r download_link_national_data("ras_gendereq_all", "commute", "lsoa", formats = c('tif'))` ; Go Dutch `r download_link_national_data("ras_dutch_all", "commute", "lsoa", formats = c('tif'))` ; Ebikes `r download_link_national_data("ras_ebike_all", "commute", "lsoa", formats = c('tif'))`</li>
          </ul>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <p>Please see the codebooks for a description of the variables included in these download files, and User Manual for further details of how these variable were calculated.  You can also contact us at <a href='mailto:pct@pct.bike'>pct@pct.bike</a>.</p>
      </div>

    </div>
  </div>
</div>
<!--/html_preserve-->