---
output: 
  html_document:
    keep_md: false
  
---


```{r echo=FALSE}
source("../m/pct_shiny_funs.R")
sha <- readRDS("download_params_sha_current.rds")
region <- readRDS("download_params_region_current.rds")

```

<!--html_preserve-->
<div class='container'>
  <div class='row maintext' id='maintext'>
    <div class='col-md-2 text-left' style='padding-top:10px;'>
      <div style='padding-bottom:10px;'><a class='regdownloadlinks' href='#regcommutezones'>Zones data</a></div>
      <div style='padding-bottom:10px;'><a class='regdownloadlinks' href='#regcommutemsoalines'>MSOA lines data</a></div>
      <div style='padding-bottom:10px;'><a class='regdownloadlinks' href='#regcommutelsoalines'>LSOA lines data</a></div>
    </div>

    <div class='col-md-9'>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h3>Data for `r get_pretty_region_name(region$region_name)`</h3>
        <p>This page contains data downloads for `r get_pretty_region_name(region$region_name)`, the region currently displayed on the 'Map' tab. These are available as CSV files containing the zone and line baseline and scenario data, and in geographic files that can be read by R (.Rds) or GIS programs such as QGIS (.geojson).</p>
        <p>Please be aware that equivalent files for different geographies and different regions have <b>the same file name</b> when downloaded (e.g. 'z.geojson' for both the MSOA and LSOA regional zones files, for all regions).  To avoid confusion you may want to rename those files or save them in labelled folders.</p>
      </div>
      
      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h4><a name='regcommutezones'></a>Commuting data for zones</h4>
          <p>Download the Census 2011 and scenario data for zones in `r get_pretty_region_name(region$region_name)`.  These zones include all commuters who <b>live in `r get_pretty_region_name(region$region_name)`</b>.</p>
          <ul>
            <li>Zones (MSOA):`r download_link_region_data("z", "commute", "msoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("z_codebook", "commute", repo_sha = sha$repo_sha)`
            </li>
            <li>Zones (LSOA):`r download_link_region_data("z", "commute", "lsoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("z_codebook", "commute", repo_sha = sha$repo_sha)` </li>
          </ul>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h4>Commuting data for lines</h4>
        <p>Download the Census 2011 and scenario data for lines in `r get_pretty_region_name(region$region_name)`.</p>
        <p>The 'All flows' files include all commuters who <b>live or work in `r get_pretty_region_name(region$region_name)`</b>.  Destinations are grouped as 'Other' for origin-destination pairs with a fastest-route distance >30km, or with a destination outside England or Wales.  In addition, for the LSOA 'All flows' file, destinations are grouped as 'Under 3' for origin-destination pairs where the bidirectional number of commuters (by any mode) would be 1 or 2.  This is done for data protection reasons.</p>
        <p>The 'Straight lines', 'Fast route' and 'Quieter routes' files only include between-zone lines with fast route distance under 20km.  In addition, the minimum number of commuters (by any mode, in either direction) must be 10 (MSOA) or 5 (LSOA).</p>
        <p>The MSOA route network was calculated using within-region between-zone flows containing a minimum number of commuters (usually 10, but higher in large regions - see 'Region stats' tab).  The LSOA route network includes all between-zone LSOA flows with fast route distance under 20km (i.e. including inter-regional flows and with no minimum number of commuters).</p>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
         <h4><a name='regcommutemsoalines'></a>MSOA-level lines data</h4>
          <ul>
            <li>All flows (attribute data only): `r download_link_region_data("od_attributes",  "commute", "msoa", region$region_name, formats = c('csv'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Centroids & within-zone travel: `r download_link_region_data("c",  "commute", "msoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("c_codebook",  "commute", repo_sha = sha$repo_sha)`</li>
            <li>Straight lines: `r download_link_region_data("l",  "commute", "msoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("od_l_rf_codebook",  "commute", repo_sha = sha$repo_sha)`</li>
            <li>Fast routes: `r download_link_region_data("rf",  "commute", "msoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Quieter routes: `r download_link_region_data("rq", "commute", "msoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("rq_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Route network (MSOA): `r download_link_region_data("rnet", "commute", "msoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("rnet_codebook", "commute", repo_sha = sha$repo_sha)`</li>
          </ul>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <h4><a name='regcommutelsoalines'></a>LSOA-level lines data</h4>
          <ul>
            <li>All flows (attribute data only): `r download_link_region_data("od_attributes", "commute", "lsoa", region$region_name,formats = c('csv'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Centroids & within-zone travel: `r download_link_region_data("c", "commute", "lsoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("c_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Straight lines: `r download_link_region_data("l", "commute", "lsoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Fast routes: `r download_link_region_data("rf", "commute", "lsoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("od_l_rf_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Quieter routes: `r download_link_region_data("rq", "commute", "lsoa", region$region_name, formats = c('Rds', 'geojson'))` - `r download_link_codebook("rq_codebook", "commute", repo_sha = sha$repo_sha)`</li>
            <li>Route network (LSOA): Census 2011 `r download_link_region_data("ras_bicycle", "commute", "lsoa", region$region_name, formats = c('tif'))` ; Government Target `r download_link_region_data("ras_govtarget", "commute", "lsoa", region$region_name, formats = c('tif'))` ; Gender Equality `r download_link_region_data("ras_gendereq", "commute", "lsoa", region$region_name, formats = c('tif'))` ; Go Dutch `r download_link_region_data("ras_dutch", "commute", "lsoa", region$region_name, formats = c('tif'))` ; Ebikes `r download_link_region_data("ras_ebike", "commute", "lsoa", region$region_name, formats = c('tif'))`</li>
          </ul>
      </div>

      <div class='col-md-12 text-left' style='padding-top:10px;'>
        <p>Please see the codebooks for a description of the variables included in these download files, and User Manual for further details of how these variable were calculated.  You can also contact us at <a href='mailto:pct@pct.bike'>pct@pct.bike</a>.</p>
      </div>

    </div>
  </div>
</div>
<!--/html_preserve-->