#!/bin/bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

git update-server-info

BRANCH=$(git rev-parse --abbrev-ref HEAD)

git --work-tree /home/git/pct-shiny --git-dir /home/git/pct-shiny show "$BRANCH":scripts/publish-pct-shiny > /home/git/bin/publish-pct-shiny
git --work-tree /home/git/pct-shiny --git-dir /home/git/pct-shiny show "$BRANCH":scripts/update-server > /home/git/bin/update-server
/home/git/bin/publish-pct-shiny "$BRANCH"
