#!/bin/bash

# (C) 2016 NPTC
# Written by Pete Stevens of Mythic Beasts Ltd and Nikolai Berkoff
# to support NPTC production deployment

set +e

VAR_DIR="/home/git/var-shiny/"
WAIT_SECONDS=0
BRANCH=$1
SHINY_APP_DIR="pct-shiny"
DATA_GIT="pct-outputs-regional-R"

while [ "$WAIT_SECONDS" -lt 120 -a -e ${VAR_DIR}.deploy-shiny-lock ]; do
  echo "Currently deploying. Waiting for ${VAR_DIR}.deploy-shiny-lock for another $((120-WAIT_SECONDS)) seconds"
  WAIT_SECONDS=$((WAIT_SECONDS+5))
  sleep 5
done

touch ${VAR_DIR}.deploy-shiny-lock

export PATH=$PATH:/home/git/bin

echo "Check out the latest version of ${BRANCH} into our temp directory"
rm -rf ${VAR_DIR}${SHINY_APP_DIR}
mkdir -p ${VAR_DIR}${SHINY_APP_DIR}
git --git-dir /home/git/pct-shiny --work-tree ${VAR_DIR}${SHINY_APP_DIR} checkout ${BRANCH} -f
git --git-dir /home/git/pct-shiny rev-parse --short HEAD > ${VAR_DIR}${SHINY_APP_DIR}/repo_sha

echo "Git fetch the data"
git -C /home/git/${DATA_GIT} fetch

DATASHA=`cat ${VAR_DIR}${SHINY_APP_DIR}/data_sha`

echo "Checkout ${DATASHA} version of the data"
git -C /home/git/${DATA_GIT} checkout $DATASHA -f

if [[ $(hostname -s) = "npct0" ]]; then
  cp ${VAR_DIR}${SHINY_APP_DIR}/static/robots.txt ${VAR_DIR}${SHINY_APP_DIR}/regions_www/robots.txt
  update-server npct0
else
  echo "Update the first server, then the second"
  update-server npt1.vs.mythic-beasts.com
  update-server npt2.vs.mythic-beasts.com
fi

rm ${VAR_DIR}.deploy-shiny-lock
